### ISSUE TITLE
gson.toJson 抛出 java.lang.AssertionError: java.lang.NoSuchFieldException: ONLINE

### ISSUE THREAD

**Issue by meijieman** [google/gson#2038]
# Gson version

com.google.code.gson:gson:2.8.0

# Java / Android version

Android 9+as arctic fox

# Used tools

- [ ] Maven; version: 
- [x] Gradle; version:  api 'com.google.code.gson:gson:2.8.0'
- [ ] ProGuard (attach the configuration file please); version: 
- [ ] ...

# Description

new Gson().toJsont(object); enter crash.

found into this code
![image](https://user-images.githubusercontent.com/19690896/147338227-060a8950-d526-497f-a335-5349bfe2b4a3.png)

why **throw new AssertionError(e);** ， not **NoSuchFieldException**

## Expected behavior

not crash!!!

## Actual behavior

crashed !!! even add try-catch(Exception e)

# Reproduction steps

1. ...
2. ...

# Exception stack trace

```
java.lang.AssertionError: java.lang.NoSuchFieldException: ONLINE
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(TypeAdapters.java:808)
        at com.google.gson.internal.bind.TypeAdapters$30.create(TypeAdapters.java:834)
        at com.google.gson.Gson.getAdapter(Gson.java:423)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:115)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:164)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
        at com.google.gson.Gson.getAdapter(Gson.java:423)
        at com.google.gson.Gson.toJson(Gson.java:661)
        at com.google.gson.Gson.toJson(Gson.java:648)
        at com.google.gson.Gson.toJson(Gson.java:603)
        at com.google.gson.Gson.toJson(Gson.java:583)
        at com.xxx.util.json.JsonUtil.toJson(JsonUtil.java:204)
```

**Comment by meijieman** [comment]
use `JSON.toJSONString(object) `, output is ok

version:  'com.alibaba:fastjson:1.1.70.android'

**Comment by meijieman** [comment]
i update gson to  'com.google.code.gson:gson:2.8.9'
find not crash, but lost some field.

**Comment by Marcono1234** [comment]
Could you please verify whether you are using ProGuard? In 2.8.8 an issue with enum constant names and ProGuard usage was fixed (#1495). The `AssertionError` you are experiencing sounds like that issue.

Most likely obfuscation performed by ProGuard is causing the issues you are seeing. Please either edit your ProGuard config to not obfuscate or shrink your model classes you are using with Gson, or use Gson's [`@SerializedName` annotation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/annotations/SerializedName.html) to specify the field names, and to not be affected by ProGuard field name obfuscation.

----

Note that I am not a member of this project.

**Comment by meijieman** [comment]
> Could you please verify whether you are using ProGuard? In 2.8.8 an issue with enum constant names and ProGuard usage was fixed (#1495). The `AssertionError` you are experiencing sounds like that issue.
> 
> Most likely obfuscation performed by ProGuard is causing the issues you are seeing. Please either edit your ProGuard config to not obfuscate or shrink your model classes you are using with Gson, or use Gson's [`@SerializedName` annotation](https://javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/annotations/SerializedName.html) to specify the field names, and to not be affected by ProGuard field name obfuscation.
> 
> Note that I am not a member of this project.

yes, there have enum constant that using ProGuard, but this model classes in third part jar, so i cannot modify this code.
i saw the  #1495 , and update to `com.google.code.gson:gson:2.8.9` , it's not crash, but leak some of variable。
still have problem。

**Comment by Marcono1234** [comment]
It should also be possible to specify ProGuard _keep_ settings for third party libraries, see for example [this StackOverflow answer](https://stackoverflow.com/a/4505108).

However, in general you should be careful when using Gson on third party classes or JDK classes. Gson by default gets private fields of classes, even though the author might not have intended them to be used publicly. This could cause your application to break when the author of the library changes the internal implementation and removes or renames those private fields.
Though, if you only use Gson for an enum class from a third party library, then that is most likely safe because Gson serializes and deserializes the names of the public enum constants.

**Comment by meijieman** [comment]
> It should also be possible to specify ProGuard _keep_ settings for third party libraries, see for example [this StackOverflow answer](https://stackoverflow.com/a/4505108).
> 
> However, in general you should be careful when using Gson on third party classes or JDK classes. Gson by default gets private fields of classes, even though the author might not have intended them to be used publicly. This could cause your application to break when the author of the library changes the internal implementation and removes or renames those private fields. Though, if you only use Gson for an enum class from a third party library, then that is most likely safe because Gson serializes and deserializes the names of the public enum constants.

emmm，first  the third party library made ProGuard, not my app, so i can do nothing of obfuscation.
then, i just use Gson#toJson for  log it's content. is ok if it Obfuscation.
and i thought is **a bug for gson** leak variable.(i tried use fastjson, and it work ok.)
i hope gson can fix it.

**Comment by Marcono1234** [comment]
> i thought is a bug for gson leak variable.(i tried use fastjson, and it work ok.)

Could you please create a small complete example project which can be used to reproduce this with Gson? (And ideally also showing how it correctly works with Fastjson.) Otherwise it is difficult to find out what is causing this issue.

**Comment by meijieman** [comment]
> > i thought is a bug for gson leak variable.(i tried use fastjson, and it work ok.)
> 
> Could you please create a small complete example project which can be used to reproduce this with Gson? (And ideally also showing how it correctly works with Fastjson.) Otherwise it is difficult to find out what is causing this issue.

i upload a test project on github. address link: [GsonTest](https://github.com/meijieman/GsonTest)
the output log in `https://github.com/meijieman/GsonTest/blob/master/REAMDE.md`

THX!

**Comment by Marcono1234** [comment]
Thank you! It looks like the additional JSON properties, such as `leftValidDays`, `mixSuccess` or `notifyMessage`, are read by Fastjson from the getter methods of the class (for example `getLeftValidDays()`), but there are no corresponding fields for them. Gson unfortunately does not support getter methods, it only support fields, see #232.

**Comment by meijieman** [comment]
i see now. its not a normal model classes.
thanks~

**Comment by eamonnmcmanus** [comment]
It looks as if the problem here is as described [above](https://github.com/google/gson/issues/2038#issuecomment-1001600466), namely that Gson currently doesn't support getter methods. Since that's covered by #232, I'm going to close this, but feel free to reopen if needed.
